"""Coordinates browser-based OAuth redirects between the MCP SDK and MCPolis.

The OAuth state parameter is replaced with a signed HMAC token so that the
callback can identify (org_id, upstream_id, user_id) without an in-memory
lookup. This survives server restarts: even if the in-memory PendingAuth
is gone, the callback can verify the token and store the auth code on
disk for the next polling connect attempt.
"""
from __future__ import annotations

import asyncio
import time
from dataclasses import dataclass, field
from urllib.parse import parse_qs, urlencode, urlparse, urlunparse

import structlog

from mcpolis.adapters.auth.hmac_token import sign_token

logger: structlog.stdlib.BoundLogger = structlog.get_logger(__name__)

# How long to wait for the user to complete auth in the browser
AUTH_TIMEOUT = 300  # 5 minutes

# Signed state tokens are valid for 10 minutes
STATE_TOKEN_MAX_AGE = 600


class UpstreamUnreachableError(RuntimeError):
    """Raised by ``wait_for_redirect_or_refresh`` when the background
    token-acquisition task hit a hard failure (e.g. upstream returned
    5xx) before either a redirect URL or a silent refresh could happen.

    Carries a user-facing message so the connect endpoint can surface
    the actual problem instead of the generic discovery-timeout text.
    """

    def __init__(self, user_message: str) -> None:
        super().__init__(user_message)
        self.user_message = user_message


@dataclass
class PendingAuth:
    """State for a single in-flight OAuth flow."""

    org_id: str
    upstream_id: str
    user_id: str
    signing_key: bytes = field(repr=False)
    redirect_url: str | None = None
    auth_code: str | None = None
    auth_state: str | None = None
    tokens_refreshed: bool = False
    failure_message: str | None = None
    _event: asyncio.Event = field(default_factory=asyncio.Event)
    _redirect_event: asyncio.Event = field(
        default_factory=asyncio.Event
    )
    _tokens_refreshed_event: asyncio.Event = field(
        default_factory=asyncio.Event
    )
    _failed_event: asyncio.Event = field(
        default_factory=asyncio.Event
    )

    async def redirect_handler(self, url: str) -> None:
        """Called by the MCP SDK when it needs the user to authorize.

        Replaces the upstream's random ``state`` query-param with a signed
        HMAC token that encodes (org_id, upstream_id, user_id,
        original_state). The callback then verifies the signature and
        recovers these fields without an in-memory lookup — so org
        scoping survives the round-trip even if the user switched orgs
        in their dashboard session mid-flow.
        """
        parsed = urlparse(url)
        params = parse_qs(parsed.query, keep_blank_values=True)

        # Extract the original state generated by the upstream
        original_state_values = params.get("state", [])
        original_state = original_state_values[0] if original_state_values else ""
        self.auth_state = original_state

        # Build a signed state token
        signed_state = sign_token(
            {
                "org": self.org_id,
                "uid": self.upstream_id,
                "usr": self.user_id,
                "ost": original_state,
                "iat": time.time(),
            },
            self.signing_key,
        )

        # Replace state in the URL
        params["state"] = [signed_state]
        flat_params: dict[str, str] = {k: v[0] for k, v in params.items()}
        new_query = urlencode(flat_params)
        new_url = urlunparse(parsed._replace(query=new_query))

        self.redirect_url = new_url
        self._redirect_event.set()

    async def callback_handler(self) -> tuple[str, str | None]:
        """Called by the MCP SDK to wait for the auth code.

        Blocks until ``complete()`` is called (from the callback endpoint).
        """
        await asyncio.wait_for(self._event.wait(), timeout=AUTH_TIMEOUT)
        if self.auth_code is None:
            raise ValueError("OAuth callback completed without auth code")
        return (self.auth_code, self.auth_state)

    def complete(self, code: str, state: str | None) -> None:
        """Signal that the callback has arrived with the auth code."""
        self.auth_code = code
        self.auth_state = state
        self._event.set()

    def mark_tokens_refreshed(self) -> None:
        """Signal that tokens were refreshed without a browser redirect."""
        self.tokens_refreshed = True
        self._tokens_refreshed_event.set()

    def mark_failed(self, user_message: str) -> None:
        """Signal that the background token-acquisition task hit a hard
        failure — short-circuits the 30s wait so the connect endpoint
        can surface the real error instead of timing out generically.
        """
        self.failure_message = user_message
        self._failed_event.set()

    async def wait_for_redirect_or_refresh(self) -> str | None:
        """Wait for either a redirect URL, a silent token refresh, or
        a hard failure from the background token-acquisition task.

        Returns the redirect URL if a browser flow is needed, or
        ``None`` if tokens were refreshed silently. Raises
        ``UpstreamUnreachableError`` (with a user-facing message) if
        the background task signalled failure, or ``TimeoutError`` if
        none of the three fired within the deadline.
        """
        redirect_task = asyncio.create_task(self._redirect_event.wait())
        refresh_task = asyncio.create_task(self._tokens_refreshed_event.wait())
        failed_task = asyncio.create_task(self._failed_event.wait())

        done, pending = await asyncio.wait(
            [redirect_task, refresh_task, failed_task],
            timeout=30,
            return_when=asyncio.FIRST_COMPLETED,
        )

        for task in pending:
            task.cancel()

        if not done:
            raise TimeoutError("Timed out waiting for OAuth flow")

        if self.failure_message is not None:
            raise UpstreamUnreachableError(self.failure_message)
        if self.tokens_refreshed:
            return None
        assert self.redirect_url is not None
        return self.redirect_url


class PendingAuthCoordinator:
    """Manages pending OAuth flows across all orgs, users and upstreams.

    State lookup on callback is done via signed HMAC tokens (stateless),
    so this coordinator only needs to hold PendingAuth objects by their
    (org_id, upstream_id, user_id) key for the brief code hand-off to
    the SDK. Keying on org_id too prevents a superadmin who drives OAuth
    in two orgs in parallel from overwriting one flow with the other.
    """

    def __init__(self, signing_key: bytes) -> None:
        self._signing_key = signing_key
        self._pending: dict[tuple[str, str, str], PendingAuth] = {}

    @property
    def signing_key(self) -> bytes:
        return self._signing_key

    def create_pending(
        self, org_id: str, upstream_id: str, user_id: str
    ) -> PendingAuth:
        """Create a new pending auth flow."""
        key = (org_id, upstream_id, user_id)
        # Clean up any existing pending auth for this key
        self._pending.pop(key, None)

        pending = PendingAuth(
            org_id=org_id,
            upstream_id=upstream_id,
            user_id=user_id,
            signing_key=self._signing_key,
        )
        self._pending[key] = pending
        return pending

    def complete_by_key(
        self,
        org_id: str,
        upstream_id: str,
        user_id: str,
        code: str,
        original_state: str | None,
    ) -> PendingAuth | None:
        """Complete a pending auth by (org_id, upstream_id, user_id).

        Called by the callback route after verifying the signed state token.
        Returns the PendingAuth if found in memory, None otherwise
        (e.g. after a server restart).
        """
        key = (org_id, upstream_id, user_id)
        pending = self._pending.pop(key, None)
        if pending is None:
            return None
        pending.complete(code, original_state)
        return pending

    def get_pending(
        self, org_id: str, upstream_id: str, user_id: str
    ) -> PendingAuth | None:
        """Get an existing pending auth flow."""
        return self._pending.get((org_id, upstream_id, user_id))

    def cleanup(self, org_id: str, upstream_id: str, user_id: str) -> None:
        """Remove a pending auth flow."""
        key = (org_id, upstream_id, user_id)
        self._pending.pop(key, None)
